wit_bindgen::generate!({
    path: "wit",
    world: "web-search-agent",
    generate_all,
});

// Export path for handler types.
use exports::wasm_af::agent::handler::{AgentError, Guest, TaskInput, TaskOutput};
// ErrorCode lives in the imported types interface, not in handler.
use crate::wasm_af::agent::types::ErrorCode;

// wasi:config/runtime is generated by wit-bindgen into the `crate::wasi` module.
// Use the `crate::` prefix to avoid ambiguity with the `wasi` crate below.
use crate::wasi::config::runtime as config;

// wasmcloud:secrets — link-scoped secret delivery from the wasmCloud host.
// The API key is never stored in named config (plaintext); the host retrieves
// it from the configured secrets backend and delivers it as an opaque handle.
use crate::wasmcloud::secrets::reveal::reveal as reveal_secret;
use crate::wasmcloud::secrets::store::{get as get_secret, SecretValue};

// WASI 0.2 HTTP — pre-built bindings from the `wasi` crate (not regenerated by wit-bindgen).
// The `::wasi` prefix selects the *crate* rather than the generated module.
use ::wasi::http::outgoing_handler;
use ::wasi::http::types::{Fields, IncomingBody, Method, OutgoingRequest, Scheme};
use ::wasi::io::poll::poll as wasi_poll;
use ::wasi::io::streams::StreamError;

// ---------------------------------------------------------------------------
// Component registration
// ---------------------------------------------------------------------------

struct Component;
export!(Component);

// ---------------------------------------------------------------------------
// Request / response shapes
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize)]
struct SearchRequest {
    query: String,
    #[serde(default)]
    count: Option<u32>,
    /// Optional allow-list of URL prefixes. Results whose URL does not start
    /// with any prefix are dropped. Overridden by the `url_allow_prefixes`
    /// wasmCloud config key (comma-separated).
    #[serde(default)]
    url_allow_prefixes: Vec<String>,
}

#[derive(serde::Serialize)]
struct SearchOutput {
    query: String,
    results: Vec<SearchResult>,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct SearchResult {
    title: String,
    url: String,
    snippet: String,
}

// Brave Search API response (only the fields we use)
#[derive(serde::Deserialize)]
struct BraveResponse {
    web: Option<BraveWeb>,
}

#[derive(serde::Deserialize)]
struct BraveWeb {
    results: Vec<BraveResult>,
}

#[derive(serde::Deserialize)]
struct BraveResult {
    title: String,
    url: String,
    description: Option<String>,
}

// ---------------------------------------------------------------------------
// Agent handler
// ---------------------------------------------------------------------------

impl Guest for Component {
    fn execute(input: TaskInput) -> Result<TaskOutput, AgentError> {
        // 1. Parse input payload.
        let req: SearchRequest =
            serde_json::from_str(&input.payload).map_err(|e| AgentError {
                code: ErrorCode::InvalidInput,
                message: format!("payload parse error: {e}"),
            })?;

        // 2. Check for mock mode (set config key `mock_results=true` for local dev
        //    when no search API key is available).
        let mock_mode = config::get("mock_results")
            .unwrap_or(None)
            .map(|v: String| v.trim().eq_ignore_ascii_case("true"))
            .unwrap_or(false);

        if mock_mode {
            let results = mock_results(&req.query);
            let payload = serde_json::to_string(&SearchOutput {
                query: req.query.clone(),
                results,
            })
            .map_err(|e| AgentError {
                code: ErrorCode::Internal,
                message: format!("serialization error: {e}"),
            })?;
            return Ok(TaskOutput { payload, metadata: vec![] });
        }

        // 3. Brave Search API key from the wasmCloud secrets backend.
        //    The key is delivered as a link-scoped secret (`brave-secrets`) wired
        //    to this component in the WADM manifest.  It is never stored in named
        //    config (plaintext); the host retrieves it from the secrets backend and
        //    provides an opaque handle that is only revealed here, immediately before
        //    use.  See deploy/wadm.yaml and deploy/setup.sh for configuration.
        //
        //    Sign up at https://brave.com/search/api/ (free tier: 2 000 queries/month).
        let secret_handle = get_secret("brave_api_key").map_err(|e| AgentError {
            code: ErrorCode::Internal,
            message: format!("failed to retrieve brave_api_key secret: {:?}", e),
        })?;
        let api_key = match reveal_secret(&secret_handle) {
            SecretValue::String(s) => s,
            SecretValue::Bytes(b) => String::from_utf8(b).map_err(|e| AgentError {
                code: ErrorCode::Internal,
                message: format!("brave_api_key is not valid UTF-8: {e}"),
            })?,
        };

        // 3. URL allow-list: config key `url_allow_prefixes` (comma-separated) takes
        //    priority over the payload field.  This list is also passed as
        //    `allowed_hosts` in the HTTP link's SourceConfig so that a capability
        //    provider honouring that key enforces the restriction at the network
        //    level.  The check below is the application-layer enforcement and runs
        //    BEFORE the outgoing request is made, so an injection in the query
        //    string cannot redirect the agent to an unlisted endpoint.
        let config_prefixes: Vec<String> = config::get("url_allow_prefixes")
            .unwrap_or(None)
            .map(|v: String| {
                v.split(',')
                    .map(|s: &str| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();

        let allow_prefixes = if !config_prefixes.is_empty() {
            config_prefixes
        } else {
            req.url_allow_prefixes.clone()
        };

        // Validate the outgoing request endpoint BEFORE calling
        // outgoing_handler::handle().  The Brave Search base URL is hard-coded in
        // brave_search(), but this check ensures any future URL-parameterised
        // variant is also gated.
        let api_base = "https://api.search.brave.com";
        if !allow_prefixes.is_empty()
            && !allow_prefixes.iter().any(|pfx| api_base.starts_with(pfx.as_str()))
        {
            return Err(AgentError {
                code: ErrorCode::CapabilityFailure,
                message: format!(
                    "search endpoint {api_base} is not in url_allow_prefixes; \
                     request blocked before network I/O"
                ),
            });
        }

        // 4. Execute the search.
        let count = req.count.unwrap_or(5).min(20);
        let results = brave_search(&req.query, count, &api_key).map_err(|e| AgentError {
            code: ErrorCode::CapabilityFailure,
            message: format!("search failed: {e}"),
        })?;

        // 5. Serialize and return.
        let payload = serde_json::to_string(&SearchOutput {
            query: req.query.clone(),
            results,
        })
        .map_err(|e| AgentError {
            code: ErrorCode::Internal,
            message: format!("serialization error: {e}"),
        })?;

        Ok(TaskOutput {
            payload,
            metadata: vec![],
        })
    }
}

// ---------------------------------------------------------------------------
// HTTP helpers
// ---------------------------------------------------------------------------

fn brave_search(query: &str, count: u32, api_key: &str) -> Result<Vec<SearchResult>, String> {
    let path = format!(
        "/res/v1/web/search?q={}&count={}",
        percent_encode(query),
        count
    );

    // Build request.
    let headers = Fields::new();
    headers
        .append(
            &"X-Subscription-Token".to_string(),
            &api_key.as_bytes().to_vec(),
        )
        .map_err(|e| format!("header append error: {:?}", e))?;
    headers
        .append(&"Accept".to_string(), &b"application/json".to_vec())
        .map_err(|e| format!("header append error: {:?}", e))?;

    let request = OutgoingRequest::new(headers);
    request
        .set_method(&Method::Get)
        .map_err(|_| "set_method failed".to_string())?;
    request
        .set_scheme(Some(&Scheme::Https))
        .map_err(|_| "set_scheme failed".to_string())?;
    request
        .set_authority(Some("api.search.brave.com"))
        .map_err(|_| "set_authority failed".to_string())?;
    request
        .set_path_with_query(Some(&path))
        .map_err(|_| "set_path_with_query failed".to_string())?;

    // Send.
    let future_resp = outgoing_handler::handle(request, None)
        .map_err(|e| format!("outgoing_handler::handle error: {:?}", e))?;

    // Block until response is available.
    let pollable = future_resp.subscribe();
    wasi_poll(&[&pollable]);
    drop(pollable);

    // FutureIncomingResponse::get returns:
    //   Option<          -- None if not ready yet
    //     Result<        -- Err(()) if the future was already consumed
    //       Result<IncomingResponse, ErrorCode>,  -- the actual HTTP result
    //       ()
    //     >
    //   >
    let response = future_resp
        .get()
        .ok_or_else(|| "future not ready after poll".to_string())?
        .map_err(|_| "future already consumed".to_string())?
        .map_err(|e| format!("HTTP transport error: {:?}", e))?;

    let status = response.status();
    if !(200..300).contains(&status) {
        return Err(format!("Brave Search returned HTTP {status}"));
    }

    // Read body.
    let body = response
        .consume()
        .map_err(|_| "response body already consumed".to_string())?;
    let stream = body
        .stream()
        .map_err(|_| "response stream already taken".to_string())?;

    let mut data: Vec<u8> = Vec::new();
    loop {
        let p = stream.subscribe();
        wasi_poll(&[&p]);
        match stream.read(65536) {
            Ok(chunk) if chunk.is_empty() => break, // EOF — ready but no bytes means closed
            Ok(chunk) => data.extend_from_slice(&chunk),
            Err(StreamError::Closed) => break,
            Err(e) => return Err(format!("stream read error: {:?}", e)),
        }
    }
    drop(stream);
    IncomingBody::finish(body);

    // Parse Brave response.
    let brave: BraveResponse =
        serde_json::from_slice(&data).map_err(|e| format!("JSON parse error: {e}"))?;

    let results = brave
        .web
        .unwrap_or(BraveWeb { results: vec![] })
        .results
        .into_iter()
        .map(|r| SearchResult {
            title: r.title,
            url: r.url,
            snippet: r.description.unwrap_or_default(),
        })
        .collect();

    Ok(results)
}

/// Returns hard-coded stub results for local development (no API key required).
/// Enable with `wash config put web-search-config mock_results=true`.
fn mock_results(query: &str) -> Vec<SearchResult> {
    vec![
        SearchResult {
            title: format!("Mock result 1 for: {query}"),
            url: "https://example.com/result-1".to_string(),
            snippet: "This is a mock search result for local development. \
                      Set mock_results=false and provide brave_api_key for real results."
                .to_string(),
        },
        SearchResult {
            title: format!("Mock result 2 for: {query}"),
            url: "https://example.com/result-2".to_string(),
            snippet: "Another mock result. The summarizer will receive these and \
                      call the LLM to produce a summary."
                .to_string(),
        },
        SearchResult {
            title: "wasm-af documentation".to_string(),
            url: "https://github.com/jolucas/wasm-af".to_string(),
            snippet: "WebAssembly agent framework built on wasmCloud. \
                      Policy-gated, orchestrated WASM agents."
                .to_string(),
        },
    ]
}

/// Percent-encode a string for use in a URL query parameter value.
/// Spaces become `+`; all other non-unreserved bytes are %-encoded.
fn percent_encode(s: &str) -> String {
    let mut out = String::with_capacity(s.len() * 3);
    for byte in s.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(byte as char)
            }
            b' ' => out.push('+'),
            b => out.push_str(&format!("%{b:02X}")),
        }
    }
    out
}
